katrinagh/Helicia

Gemfile, Gemfile.lock, config/initializers/simple_form.rb, config/initializers/simple_form_bootstrap.rb, config/locales/simple_form.en.yml, lib/templates/erb/scaffold/_form.html.erb
Rajouté gem simple-form avec ses temnplates
=> simpe form

app/models/article.rb, app/models/article_order.rb, app/models/order.rb, app/models/store.rb, app/models/user.rb, db/migrate/20230606082713_create_stores.rb, db/migrate/20230606082937_create_articles.rb, db/migrate/20230606084138_create_users.rb, db/migrate/20230606111037_create_orders.rb, db/migrate/20230606111154_create_article_orders.rb, db/schema.rb, test/fixtures/article_orders.yml, test/fixtures/articles.yml, test/fixtures/orders.yml, test/fixtures/stores.yml, test/fixtures/users.yml, test/models/article_order_test.rb, test/models/article_test.rb, test/models/order_test.rb, test/models/store_test.rb, test/models/user_test.rb
=> All story tables and models

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230606125048_add_devise_to_users.rb
=> Installing devise

app/models/store.rb, db/schema.rb, db/seeds.rb, node_modules/.yarn-integrity
8 stores, 10 articles par store donc 80 articles :) 
ET CA MARCHE!!!!
=> fixing seed

app/models/article.rb, app/models/order.rb, app/models/store.rb, app/models/user.rb
=> Updating all models

app/models/article.rb, app/models/store.rb
Removing has_one_attached :photo
=> removing attached photo for active storage

app/assets/stylesheets/pages/_index.scss, app/controllers/stores_controller.rb, app/views/stores/index.html.erb, config/routes.rb
=> index_stores_controller_routes

app/views/stores/index.html.erb
=> Adding link to go on show

app/controllers/stores_controller.rb, app/views/stores/show.html.erb
=> Show for stores, WIP

app/controllers/application_controller.rb, app/models/article.rb, app/models/article_order.rb, app/models/order.rb, app/models/store.rb, app/views/stores/show.html.erb, db/schema.rb
=> validations

app/controllers/articles_controller.rb, app/views/articles/show.html.erb, app/views/stores/show.html.erb, config/routes.rb, test/controllers/articles_controller_test.rb
=> Show for article on store

app/controllers/article_orders_controller.rb, app/controllers/orders_controller.rb, app/views/article_orders/index.html.erb, app/views/articles/show.html.erb, app/views/orders/index.html.erb, config/routes.rb, test/controllers/article_orders_controller_test.rb, test/controllers/orders_controller_test.rb
=> Article order

app/controllers/article_orders_controller.rb, app/controllers/orders_controller.rb, app/models/order.rb, app/models/user.rb
=> changed user to have only one order

app/views/stores/show.html.erb
les prix s'affiche 2.50 au lieux de 2.5
on peut appuyer sur les cartes plutot que sur les titres
=> show de stores

app/controllers/article_orders_controller.rb, app/views/articles/show.html.erb, app/views/orders/index.html.erb, app/views/stores/show.html.erb
=> fixing order index

app/views/articles/show.html.erb
fil d'ariane rectifier et chiffre a deux decimales
=> chiffre a deux decimal fixer

app/views/stores/index.html.erb
changement en étoile pour le rating
=> change rating with star

app/controllers/application_controller.rb, app/controllers/orders_controller.rb, app/controllers/stores_controller.rb, app/models/article.rb, app/models/article_order.rb, app/models/order.rb, app/views/articles/_article_items.html.erb, app/views/articles/show.html.erb, app/views/orders/_article_items.html.erb, app/views/orders/_order.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, config/routes.rb, node_modules/.yarn-integrity
-> add items to cart
-> update items in cart
-> delete items from cart
=> Adding cart

app/views/devise/registrations/new.html.erb
Just email and password required to sign-in
=> fast check-in

app/controllers/application_controller.rb, app/views/articles/show.html.erb, app/views/shared/_navbar.html.erb
FIxed problem when @order does not exist (prevent crash with a if present condition)
=> fixed some links problems

app/views/orders/_order.html.erb, app/views/shared/_navbar.html.erb
Link to store/:id at place of stores
=> fixing navbar div and links

app/views/articles/show.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb, node_modules/.yarn-integrity
=> fixing bug

app/views/articles/show.html.erb
=> adding popup

app/controllers/application_controller.rb, app/controllers/articles_controller.rb, app/controllers/orders_controller.rb, app/views/articles/show.html.erb, app/views/shared/_jauge.html.erb, app/views/shared/_navbar.html.erb
=> fixing bugs

app/controllers/application_controller.rb, app/controllers/orders_controller.rb, app/views/articles/show.html.erb, app/views/orders/_order.html.erb, app/views/orders/create.json.jbuilder
=> trying to fix cart add button bugs

app/views/articles/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_jauge.html.erb, node_modules/.yarn-integrity
=> Revert "navbar fixing work in progress"

app/views/shared/_navbar.html.erb
=> Revert "Navbar problems"

app/views/layouts/application.html.erb, app/views/orders/_credit_card.html.erb, app/views/orders/checkout.html.erb, app/views/orders/confirmation.html.erb, app/views/stores/index.html.erb, app/views/stores/show.html.erb
=> Checkout page

app/controllers/orders_controller.rb, app/views/orders/_info_window_order.html.erb, app/views/orders/checkout.html.erb, app/views/shared/_navbar.html.erb
=> bouton back du cart améliorer pour ne pas etre génant

app/assets/stylesheets/pages/_article_items.scss, app/assets/stylesheets/pages/_checkout_show.scss, app/views/orders/_article_items.html.erb, app/views/orders/_credit_card.html.erb
=> css for credit card form on checkout

app/assets/stylesheets/pages/_article.scss, app/assets/stylesheets/pages/_checkout_show.scss, app/views/stores/show.html.erb
=> Category titles on stores show

app/assets/stylesheets/pages/_article.scss, app/views/articles/show.html.erb
=> Alignement left title and description on article show

app/views/orders/_order.html.erb
=> Changed upper case to cart

app/assets/stylesheets/pages/_article_items.scss
=> margin on total cart

app/views/stores/index.html.erb
=> search results

app/assets/stylesheets/pages/_checkout_show.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/map_dynamic.scss, app/views/orders/confirmation.html.erb, app/views/stores/show.html.erb
=> taille a 90%

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_stores_index.scss, app/views/layouts/application.html.erb
=> navbar fixer en bas
